#!/usr/bin/env bash

make

TARGET_DIR="./tests"

if [ ! -d "$TARGET_DIR" ]; then
  echo "directory does not exist"
  exit 1
fi

echo "Starting tests"
echo "-------------------------------"

for file in "$TARGET_DIR"/*; do
  [ -e "$file" ] || continue
  echo -n "Running $file: "
  "$file"
done
