#!/usr/bin/env bash
set -e

TEST_DIR=$(mktemp -d)
BF_FILE="$TEST_DIR/hello.bf"

cat <<'EOF' >"$BF_FILE"
>++++++++[<+++++++++>-]<. H
---. E
+++++++.. LL
+++. O
EOF

OUTPUT=$(./build/main "$BF_FILE")

if [ "$OUTPUT" = "HELLO" ]; then
  echo "Passed"
else
  echo "Failed"
fi
